#!/bin/bash

function createProducer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/producer.gridlink.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/producer.gridlink.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-producer --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-producer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-producer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-producer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-producer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy producer's CA cert to producer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/producer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/tlscacerts/ca.crt"

  # Copy producer's CA cert to producer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/producer.gridlink.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/producer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/tlsca/tlsca.producer.gridlink.com-cert.pem"

  # Copy producer's CA cert to producer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/producer.gridlink.com/ca"
  cp "${PWD}/organizations/fabric-ca/producer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/ca/ca.producer.gridlink.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-producer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-producer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-producer --id.name produceradmin --id.secret produceradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-producer -M "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-producer -M "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls" --enrollment.profile tls --csr.hosts peer0.producer.gridlink.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/producer.gridlink.com/peers/peer0.producer.gridlink.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-producer -M "${PWD}/organizations/peerOrganizations/producer.gridlink.com/users/User1@producer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/users/User1@producer.gridlink.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://produceradmin:produceradminpw@localhost:7054 --caname ca-producer -M "${PWD}/organizations/peerOrganizations/producer.gridlink.com/users/Admin@producer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/producer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/producer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/producer.gridlink.com/users/Admin@producer.gridlink.com/msp/config.yaml"
}

function createConsumer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/consumer.gridlink.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/consumer.gridlink.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-consumer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-consumer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-consumer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-consumer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-consumer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy consumer's CA cert to consumer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/tlscacerts/ca.crt"

  # Copy consumer's CA cert to consumer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/tlsca/tlsca.consumer.gridlink.com-cert.pem"

  # Copy consumer's CA cert to consumer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/ca"
  cp "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/ca/ca.consumer.gridlink.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-consumer --id.name consumeradmin --id.secret consumeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls" --enrollment.profile tls --csr.hosts peer0.consumer.gridlink.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/peers/peer0.consumer.gridlink.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/users/User1@consumer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/users/User1@consumer.gridlink.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://consumeradmin:consumeradminpw@localhost:8054 --caname ca-consumer -M "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/users/Admin@consumer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/consumer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/consumer.gridlink.com/users/Admin@consumer.gridlink.com/msp/config.yaml"
}


function createUtilityCompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/utilitycompany.gridlink.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-utilitycompany --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-utilitycompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-utilitycompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-utilitycompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-utilitycompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy utilitycompany's CA cert to utilitycompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/tlscacerts/ca.crt"

  # Copy utilitycompany's CA cert to utilitycompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/tlsca/tlsca.utilitycompany.gridlink.com-cert.pem"

  # Copy utilitycompany's CA cert to utilitycompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/ca"
  cp "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/ca/ca.utilitycompany.gridlink.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-utilitycompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-utilitycompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-utilitycompany --id.name utilitycompanyadmin --id.secret utilitycompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-utilitycompany -M "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-utilitycompany -M "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls" --enrollment.profile tls --csr.hosts peer0.utilitycompany.gridlink.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/peers/peer0.utilitycompany.gridlink.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-utilitycompany -M "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/users/User1@utilitycompany.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/users/User1@utilitycompany.gridlink.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://utilitycompanyadmin:utilitycompanyadminpw@localhost:11054 --caname ca-utilitycompany -M "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/users/Admin@utilitycompany.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/utilitycompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/utilitycompany.gridlink.com/users/Admin@utilitycompany.gridlink.com/msp/config.yaml"
}

function createRegulatoryBody() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/regulatorybody.gridlink.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:12054 --caname ca-regulatorybody --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-regulatorybody.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-regulatorybody.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-regulatorybody.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-regulatorybody.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy regulatorybody's CA cert to regulatorybody's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/tlscacerts/ca.crt"

  # Copy regulatorybody's CA cert to regulatorybody's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/tlsca/tlsca.regulatorybody.gridlink.com-cert.pem"

  # Copy regulatorybody's CA cert to regulatorybody's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/ca"
  cp "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/ca/ca.regulatorybody.gridlink.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-regulatorybody --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-regulatorybody --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-regulatorybody --id.name regulatorybodyadmin --id.secret regulatorybodyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-regulatorybody -M "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-regulatorybody -M "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls" --enrollment.profile tls --csr.hosts peer0.regulatorybody.gridlink.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/peers/peer0.regulatorybody.gridlink.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:12054 --caname ca-regulatorybody -M "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/users/User1@regulatorybody.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/users/User1@regulatorybody.gridlink.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://regulatorybodyadmin:regulatorybodyadminpw@localhost:12054 --caname ca-regulatorybody -M "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/users/Admin@regulatorybody.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/regulatorybody/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/regulatorybody.gridlink.com/users/Admin@regulatorybody.gridlink.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/gridlink.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/gridlink.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/gridlink.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/gridlink.com/msp/tlscacerts/tlsca.gridlink.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/gridlink.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/gridlink.com/tlsca/tlsca.gridlink.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls" --enrollment.profile tls --csr.hosts orderer.gridlink.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/gridlink.com/orderers/orderer.gridlink.com/msp/tlscacerts/tlsca.gridlink.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/gridlink.com/users/Admin@gridlink.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/gridlink.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/gridlink.com/users/Admin@gridlink.com/msp/config.yaml"
}

createProducer
createConsumer
createUtilityCompany
createRegulatoryBody
createOrderer
